site_name: Strada.jl

pages:
- [index.md, Index]
- [tutorial.md, Tutorial]
- [network.md, Network]
- [api/layers.md, Layers]
- [training.md, Training]
- [examples.md, Examples]
- [api/Strada.md, API]
